name: ek_widget
description: Bu paket Enes KOC un ulusturdugu widgetleri kapsar "This packet is inculude make widgets of Enes KOÇ
version: 0.0.1

# dart fix --apply  (const ekleyen terminal kodu)

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  animated_button: ^0.2.0
  avatar_glow: ^2.0.2
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.1.1
  google_fonts: ^4.0.0
  image_network: ^2.5.1
  progress_state_button: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

































